inventory_types:
  - PLAYER
  - CHEST
  - BARREL
  - ENDER_CHEST
  - HOPPER
  - SHULKER_BOX

material_groups:
  - - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG

  - - STRIPPED_OAK_LOG
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_BIRCH_LOG
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_ACACIA_LOG
    - STRIPPED_DARK_OAK_LOG

  - - OAK_WOOD
    - SPRUCE_WOOD
    - BIRCH_WOOD
    - JUNGLE_WOOD
    - ACACIA_WOOD
    - DARK_OAK_WOOD

  - - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS

  - - OAK_SLAB
    - SPRUCE_SLAB
    - BIRCH_SLAB
    - JUNGLE_SLAB
    - ACACIA_SLAB
    - DARK_OAK_SLAB

  - - OAK_STAIRS
    - SPRUCE_STAIRS
    - BIRCH_STAIRS
    - JUNGLE_STAIRS
    - ACACIA_STAIRS
    - DARK_OAK_STAIRS

  - - OAK_FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - ACACIA_FENCE
    - DARK_OAK_FENCE

  - - OAK_LEAVES
    - SPRUCE_LEAVES
    - BIRCH_LEAVES
    - JUNGLE_LEAVES
    - ACACIA_LEAVES
    - DARK_OAK_LEAVES

  - - OAK_SAPLING
    - SPRUCE_SAPLING
    - BIRCH_SAPLING
    - JUNGLE_SAPLING
    - ACACIA_SAPLING
    - DARK_OAK_SAPLING

  - - OAK_SIGN
    - SPRUCE_SIGN
    - BIRCH_SIGN
    - JUNGLE_SIGN
    - ACACIA_SIGN
    - DARK_OAK_SIGN

  - - GRASS_BLOCK
  - - DIRT
  - - COARSE_DIRT
    - PODZOL
  - - MYCELIUM
  - - FARMLAND
    - GRASS_PATH

  - - CLAY_BALL
  - - CLAY
  - - BRICK
  - - BRICKS
    - BRICK_SLAB
    - BRICK_STAIRS
    - BRICK_WALL

  - - SAND

  - - SANDSTONE
    - SANDSTONE_SLAB
    - SANDSTONE_STAIRS

  - - SMOOTH_SANDSTONE
    - SMOOTH_SANDSTONE_SLAB
    - SMOOTH_SANDSTONE_STAIRS

  - - CUT_SANDSTONE
    - CUT_SANDSTONE_SLAB

  - - CHISELED_SANDSTONE

  - - RED_SAND

  - - RED_SANDSTONE
    - RED_SANDSTONE_SLAB
    - RED_SANDSTONE_STAIRS

  - - SMOOTH_RED_SANDSTONE
    - SMOOTH_RED_SANDSTONE_SLAB
    - SMOOTH_RED_SANDSTONE_STAIRS

  - - CUT_RED_SANDSTONE
    - CUT_RED_SANDSTONE_SLAB

  - - CHISELED_RED_SANDSTONE

  - - STONE
    - STONE_SLAB
    - STONE_STAIRS

  - - SMOOTH_STONE
    - SMOOTH_STONE_SLAB

  - - STONE_BRICKS
  - - STONE_BRICK_SLAB
    - STONE_BRICK_STAIRS
    - STONE_BRICK_WALL

  - - MOSSY_STONE_BRICKS
    - MOSSY_STONE_BRICK_SLAB
    - MOSSY_STONE_BRICK_STAIRS
    - MOSSY_STONE_BRICK_WALL

  - - CRACKED_STONE_BRICKS
    - CHISELED_STONE_BRICKS

  - - COBBLESTONE
    - COBBLESTONE_SLAB
    - COBBLESTONE_STAIRS
    - COBBLESTONE_WALL

  - - MOSSY_COBBLESTONE
    - MOSSY_COBBLESTONE_SLAB
    - MOSSY_COBBLESTONE_STAIRS
    - MOSSY_COBBLESTONE_WALL

  - - POLISHED_DIORITE
    - POLISHED_DIORITE_SLAB
    - POLISHED_DIORITE_STAIRS

  - - DIORITE
    - DIORITE_SLAB
    - DIORITE_STAIRS
    - DIORITE_WALL

  - - POLISHED_GRANITE
    - POLISHED_GRANITE_SLAB
    - POLISHED_GRANITE_STAIRS

  - - GRANITE
    - GRANITE_SLAB
    - GRANITE_STAIRS
    - GRANITE_WALL

  - - POLISHED_ANDESITE
    - POLISHED_ANDESITE_SLAB
    - POLISHED_ANDESITE_STAIRS

  - - ANDESITE
    - ANDESITE_SLAB
    - ANDESITE_STAIRS
    - ANDESITE_WALL

  - - GRAVEL

  - - WHITE_CONCRETE
    - ORANGE_CONCRETE
    - MAGENTA_CONCRETE
    - LIGHT_BLUE_CONCRETE
    - YELLOW_CONCRETE
    - LIME_CONCRETE
    - PINK_CONCRETE
    - GRAY_CONCRETE
    - LIGHT_GRAY_CONCRETE
    - CYAN_CONCRETE
    - PURPLE_CONCRETE
    - BLUE_CONCRETE
    - BROWN_CONCRETE
    - GREEN_CONCRETE
    - RED_CONCRETE
    - BLACK_CONCRETE

  - - WHITE_CONCRETE_POWDER
    - ORANGE_CONCRETE_POWDER
    - MAGENTA_CONCRETE_POWDER
    - LIGHT_BLUE_CONCRETE_POWDER
    - YELLOW_CONCRETE_POWDER
    - LIME_CONCRETE_POWDER
    - PINK_CONCRETE_POWDER
    - GRAY_CONCRETE_POWDER
    - LIGHT_GRAY_CONCRETE_POWDER
    - CYAN_CONCRETE_POWDER
    - PURPLE_CONCRETE_POWDER
    - BLUE_CONCRETE_POWDER
    - BROWN_CONCRETE_POWDER
    - GREEN_CONCRETE_POWDER
    - RED_CONCRETE_POWDER
    - BLACK_CONCRETE_POWDER

  - - TERRACOTTA
  - - WHITE_TERRACOTTA
    - ORANGE_TERRACOTTA
    - MAGENTA_TERRACOTTA
    - LIGHT_BLUE_TERRACOTTA
    - YELLOW_TERRACOTTA
    - LIME_TERRACOTTA
    - PINK_TERRACOTTA
    - GRAY_TERRACOTTA
    - LIGHT_GRAY_TERRACOTTA
    - CYAN_TERRACOTTA
    - PURPLE_TERRACOTTA
    - BLUE_TERRACOTTA
    - BROWN_TERRACOTTA
    - GREEN_TERRACOTTA
    - RED_TERRACOTTA
    - BLACK_TERRACOTTA

  - - WHITE_GLAZED_TERRACOTTA
    - ORANGE_GLAZED_TERRACOTTA
    - MAGENTA_GLAZED_TERRACOTTA
    - LIGHT_BLUE_GLAZED_TERRACOTTA
    - YELLOW_GLAZED_TERRACOTTA
    - LIME_GLAZED_TERRACOTTA
    - PINK_GLAZED_TERRACOTTA
    - GRAY_GLAZED_TERRACOTTA
    - LIGHT_GRAY_GLAZED_TERRACOTTA
    - CYAN_GLAZED_TERRACOTTA
    - PURPLE_GLAZED_TERRACOTTA
    - BLUE_GLAZED_TERRACOTTA
    - BROWN_GLAZED_TERRACOTTA
    - GREEN_GLAZED_TERRACOTTA
    - RED_GLAZED_TERRACOTTA
    - BLACK_GLAZED_TERRACOTTA

  - - GLASS
  - - WHITE_STAINED_GLASS
    - ORANGE_STAINED_GLASS
    - MAGENTA_STAINED_GLASS
    - LIGHT_BLUE_STAINED_GLASS
    - YELLOW_STAINED_GLASS
    - LIME_STAINED_GLASS
    - PINK_STAINED_GLASS
    - GRAY_STAINED_GLASS
    - LIGHT_GRAY_STAINED_GLASS
    - CYAN_STAINED_GLASS
    - PURPLE_STAINED_GLASS
    - BLUE_STAINED_GLASS
    - BROWN_STAINED_GLASS
    - GREEN_STAINED_GLASS
    - RED_STAINED_GLASS
    - BLACK_STAINED_GLASS

  - - GLASS_PANE
  - - WHITE_STAINED_GLASS_PANE
    - ORANGE_STAINED_GLASS_PANE
    - MAGENTA_STAINED_GLASS_PANE
    - LIGHT_BLUE_STAINED_GLASS_PANE
    - YELLOW_STAINED_GLASS_PANE
    - LIME_STAINED_GLASS_PANE
    - PINK_STAINED_GLASS_PANE
    - GRAY_STAINED_GLASS_PANE
    - LIGHT_GRAY_STAINED_GLASS_PANE
    - CYAN_STAINED_GLASS_PANE
    - PURPLE_STAINED_GLASS_PANE
    - BLUE_STAINED_GLASS_PANE
    - BROWN_STAINED_GLASS_PANE
    - GREEN_STAINED_GLASS_PANE
    - RED_STAINED_GLASS_PANE
    - BLACK_STAINED_GLASS_PANE

  - - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL

  - - COOKED_PORKCHOP
  - - PORKCHOP

  - - COOKED_BEEF
  - - BEEF

  - - COOKED_MUTTON
  - - MUTTON

  - - COOKED_CHICKEN
  - - CHICKEN

  - - COOKED_RABBIT
  - - RABBIT

  - - COOKED_COD
  - - COD

  - - COOKED_SALMON
  - - SALMON

  - - TROPICAL_FISH

  - - MELON_SLICE
  - - MELON
  - - MELON_SEEDS

  - - PUMPKIN_PIE
  - - PUMPKIN
  - - CARVED_PUMPKIN
    - JACK_O_LANTERN
  - - PUMPKIN_SEEDS

  - - BREAD
  - - WHEAT
  - - WHEAT_SEEDS

  - - BAKED_POTATO
  - - POTATO
  - - POISONOUS_POTATO

  - - BEETROOT
  - - BEETROOT_SEEDS
  - - BEETROOT_SOUP

  - - CAKE
  - - COOKIE
    - COCOA_BEANS

  - - CARROT
    - SWEET_BERRIES
    - RABBIT_STEW

  - - MUSHROOM_STEW
    - RED_MUSHROOM
    - BROWN_MUSHROOM

  - - DIAMOND_ORE
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - REDSTONE_ORE
    - EMERALD_ORE
    - LAPIS_ORE

  - - DIAMOND_BLOCK
    - DIAMOND

  - - GOLD_BLOCK
    - GOLD_INGOT
    - GOLD_NUGGET

  - - IRON_BLOCK
    - IRON_INGOT
    - IRON_NUGGET

  - - COAL_BLOCK
    - COAL
    - CHARCOAL

  - - REDSTONE_BLOCK
    - REDSTONE

  - - EMERALD_BLOCK
    - EMERALD

  - - LAPIS_BLOCK
    - LAPIS_LAZULI

  - - ICE
    - PACKED_ICE
    - BLUE_ICE

  - - SNOW_BLOCK
    - SNOW
    - SNOWBALL

  - - DANDELION
    - SUNFLOWER
  - - POPPY
    - RED_TULIP
    - ROSE_BUSH
  - - BLUE_ORCHID
    - CORNFLOWER
  - - ALLIUM
    - PINK_TULIP
    - LILAC
    - PEONY
  - - AZURE_BLUET
    - WHITE_TULIP
    - OXEYE_DAISY
    - LILY_OF_THE_VALLEY
  - - ORANGE_TULIP

  - - RED_DYE
    - GREEN_DYE
    - PURPLE_DYE
    - CYAN_DYE
    - LIGHT_GRAY_DYE
    - GRAY_DYE
    - PINK_DYE
    - LIME_DYE
    - YELLOW_DYE
    - LIGHT_BLUE_DYE
    - MAGENTA_DYE
    - ORANGE_DYE
    - BLUE_DYE
    - BROWN_DYE
    - BLACK_DYE
    - WHITE_DYE

  - - GRASS
    - TALL_GRASS
  - - LARGE_FERN
    - FERN
  - - DEAD_BUSH
  - - VINE
    - LILY_PAD
  - - COBWEB

  - - BROWN_MUSHROOM_BLOCK
    - RED_MUSHROOM_BLOCK
    - MUSHROOM_STEM

  - - WHITE_CARPET
    - ORANGE_CARPET
    - MAGENTA_CARPET
    - LIGHT_BLUE_CARPET
    - YELLOW_CARPET
    - LIME_CARPET
    - PINK_CARPET
    - GRAY_CARPET
    - LIGHT_GRAY_CARPET
    - CYAN_CARPET
    - PURPLE_CARPET
    - BLUE_CARPET
    - BROWN_CARPET
    - GREEN_CARPET
    - RED_CARPET
    - BLACK_CARPET

  - - WHITE_BED
    - ORANGE_BED
    - MAGENTA_BED
    - LIGHT_BLUE_BED
    - YELLOW_BED
    - LIME_BED
    - PINK_BED
    - GRAY_BED
    - LIGHT_GRAY_BED
    - CYAN_BED
    - PURPLE_BED
    - BLUE_BED
    - BROWN_BED
    - GREEN_BED
    - RED_BED
    - BLACK_BED

  - - WHITE_BANNER
    - WHITE_WALL_BANNER

  - - ORANGE_BANNER
    - ORANGE_WALL_BANNER

  - - MAGENTA_BANNER
    - MAGENTA_WALL_BANNER

  - - LIGHT_BLUE_BANNER
    - LIGHT_BLUE_WALL_BANNER

  - - YELLOW_BANNER
    - YELLOW_WALL_BANNER

  - - LIME_BANNER
    - LIME_WALL_BANNER

  - - PINK_BANNER
    - PINK_WALL_BANNER

  - - GRAY_BANNER
    - GRAY_WALL_BANNER

  - - CYAN_BANNER
    - CYAN_WALL_BANNER

  - - PURPLE_BANNER
    - PURPLE_WALL_BANNER

  - - BLUE_BANNER
    - BLUE_WALL_BANNER

  - - BROWN_BANNER
    - BROWN_WALL_BANNER

  - - GREEN_BANNER
    - GREEN_WALL_BANNER

  - - RED_BANNER
    - RED_WALL_BANNER

  - - BLACK_BANNER
    - BLACK_WALL_BANNER

  - - CREEPER_BANNER_PATTERN
    - MOJANG_BANNER_PATTERN
    - FLOWER_BANNER_PATTERN
    - SKULL_BANNER_PATTERN
    - GLOBE_BANNER_PATTERN

  - - LADDER

  - - IRON_DOOR
  - - OAK_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR

  - - OAK_FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - ACACIA_FENCE_GATE
    - DARK_OAK_FENCE_GATE

  - - IRON_TRAPDOOR
  - - OAK_TRAPDOOR
    - SPRUCE_TRAPDOOR
    - BIRCH_TRAPDOOR
    - JUNGLE_TRAPDOOR
    - ACACIA_TRAPDOOR
    - DARK_OAK_TRAPDOOR

  - - STONE_PRESSURE_PLATE
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - LIGHT_WEIGHTED_PRESSURE_PLATE

  - - OAK_PRESSURE_PLATE
    - SPRUCE_PRESSURE_PLATE
    - BIRCH_PRESSURE_PLATE
    - JUNGLE_PRESSURE_PLATE
    - ACACIA_PRESSURE_PLATE
    - DARK_OAK_PRESSURE_PLATE

  - - STONE_BUTTON
  - - OAK_BUTTON
    - SPRUCE_BUTTON
    - BIRCH_BUTTON
    - JUNGLE_BUTTON
    - ACACIA_BUTTON
    - DARK_OAK_BUTTON

  - - DISPENSER
    - DROPPER

  - - STICKY_PISTON
    - PISTON

  - - TRIPWIRE_HOOK
    - LEVER

  - - REPEATER
    - COMPARATOR
    - REDSTONE_TORCH

  - - OBSERVER
    - HOPPER

  - - DAYLIGHT_DETECTOR
    - REDSTONE_LAMP

  - - RAIL
  - - ACTIVATOR_RAIL
    - DETECTOR_RAIL
    - POWERED_RAIL

  - - MINECART
  - - CHEST_MINECART
    - FURNACE_MINECART
    - HOPPER_MINECART
    - TNT_MINECART

  - - OAK_BOAT
    - SPRUCE_BOAT
    - BIRCH_BOAT
    - JUNGLE_BOAT
    - ACACIA_BOAT
    - DARK_OAK_BOAT

  - - CHEST
    - TRAPPED_CHEST
  - - BARREL

  - - CRAFTING_TABLE

  - - FURNACE
  - - SMOKER
    - BLAST_FURNACE

  - - LOOM
    - CARTOGRAPHY_TABLE
    - FLETCHING_TABLE
    - GRINDSTONE
    - SMITHING_TABLE
    - STONECUTTER
    - LECTERN
    - COMPOSTER

  - - ENCHANTING_TABLE
  - - BOOK
    - BOOKSHELF

  - - BREWING_STAND
    - CAULDRON

  - - ANVIL
  - - CHIPPED_ANVIL
    - DAMAGED_ANVIL

  - - CAMPFIRE
  - - SCAFFOLDING
  - - BELL
    - LANTERN

  - - ARMOR_STAND
    - FLOWER_POT
    - ITEM_FRAME
    - PAINTING
    - IRON_BARS

  - - JUKEBOX
    - NOTE_BLOCK

  - - PRISMARINE_CRYSTALS
  - - PRISMARINE_SHARD

  - - PRISMARINE
    - PRISMARINE_SLAB
    - PRISMARINE_STAIRS
    - PRISMARINE_WALL

  - - PRISMARINE_BRICKS
    - PRISMARINE_BRICK_SLAB
    - PRISMARINE_BRICK_STAIRS

  - - DARK_PRISMARINE
    - DARK_PRISMARINE_SLAB
    - DARK_PRISMARINE_STAIRS

  - - SEA_LANTERN

  - - DEAD_TUBE_CORAL_BLOCK
    - DEAD_BRAIN_CORAL_BLOCK
    - DEAD_BUBBLE_CORAL_BLOCK
    - DEAD_FIRE_CORAL_BLOCK
    - DEAD_HORN_CORAL_BLOCK

  - - DEAD_TUBE_CORAL
    - DEAD_BRAIN_CORAL
    - DEAD_BUBBLE_CORAL
    - DEAD_FIRE_CORAL
    - DEAD_HORN_CORAL

  - - TUBE_CORAL
    - BRAIN_CORAL
    - BUBBLE_CORAL
    - FIRE_CORAL
    - HORN_CORAL

  - - TUBE_CORAL_FAN
    - BRAIN_CORAL_FAN
    - BUBBLE_CORAL_FAN
    - FIRE_CORAL_FAN
    - HORN_CORAL_FAN

  - - SPONGE
    - WET_SPONGE

  - - SEAGRASS
    - SEA_PICKLE
  - - KELP
    - KELP_BLOCK

  - - CONDUIT
    - NAUTILUS_SHELL
    - HEART_OF_THE_SEA

  - - TURTLE_EGG
    - SCUTE

  - - OBSIDIAN

  - - NETHERRACK
  - - SOUL_SAND
  - - MAGMA_BLOCK

  - - GLOWSTONE
    - GLOWSTONE_DUST

  - - NETHER_BRICK
    - NETHER_BRICKS
    - NETHER_BRICK_SLAB
    - NETHER_BRICK_STAIRS
    - NETHER_BRICK_WALL
    - NETHER_BRICK_FENCE

  - - RED_NETHER_BRICKS
    - RED_NETHER_BRICK_SLAB
    - RED_NETHER_BRICK_STAIRS

  - - NETHER_WART_BLOCK
    - NETHER_WART

  - - NETHER_QUARTZ_ORE
    - QUARTZ

  - - QUARTZ_BLOCK
    - QUARTZ_SLAB
    - QUARTZ_STAIRS

  - - SMOOTH_QUARTZ
    - SMOOTH_QUARTZ_SLAB
    - SMOOTH_QUARTZ_STAIRS

  - - CHISELED_QUARTZ_BLOCK
    - QUARTZ_PILLAR

  - - WITHER_ROSE
    - NETHER_STAR
    - BEACON

  - - BLAZE_ROD
    - BLAZE_POWDER

  - - GHAST_TEAR
  - - MAGMA_CREAM

  - - END_STONE

  - - END_STONE_BRICKS
    - END_STONE_BRICK_SLAB
    - END_STONE_BRICK_STAIRS
    - END_STONE_BRICK_WALL

  - - PURPUR_BLOCK
    - PURPUR_SLAB
    - PURPUR_STAIRS
  - - PURPUR_PILLAR

  - - CHORUS_FRUIT
    - POPPED_CHORUS_FRUIT

  - - CHORUS_PLANT
    - CHORUS_FLOWER

  - - END_ROD
    - END_CRYSTAL
    - ENDER_CHEST

  - - ENDER_PEARL
    - ENDER_EYE

  - - ELYTRA

  - - SHULKER_SHELL
  - - SHULKER_BOX
    - WHITE_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIME_SHULKER_BOX
    - PINK_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - RED_SHULKER_BOX
    - BLACK_SHULKER_BOX

  - - FLINT
    - STICK

  - - BAMBOO
  - - CACTUS
  - - SUGAR_CANE
    - SUGAR
    - PAPER

  - - FEATHER
  - - LEATHER
    - EGG
  - - INK_SAC
  - - RABBIT_HIDE
    - RABBIT_FOOT
  - - PHANTOM_MEMBRANE
  - - PUFFERFISH

  - - ROTTEN_FLESH
  - - STRING
    - SPIDER_EYE
    - FERMENTED_SPIDER_EYE
  - - BONE
    - BONE_MEAL
  - - GUNPOWDER
  - - SLIME_BALL
    - SLIME_BLOCK
  - - BONE
    - BONE_BLOCK

  - - SKELETON_SKULL
    - WITHER_SKELETON_SKULL
    - PLAYER_HEAD
    - ZOMBIE_HEAD
    - CREEPER_HEAD
    - DRAGON_HEAD

  - - WOODEN_SWORD
  - - WOODEN_PICKAXE
  - - WOODEN_AXE
  - - WOODEN_SHOVEL
  - - WOODEN_HOE

  - - STONE_SWORD
  - - STONE_PICKAXE
  - - STONE_AXE
  - - STONE_SHOVEL
  - - STONE_HOE

  - - IRON_SWORD
  - - IRON_PICKAXE
  - - IRON_AXE
  - - IRON_SHOVEL
  - - IRON_HOE

  - - GOLDEN_SWORD
  - - GOLDEN_PICKAXE
  - - GOLDEN_AXE
  - - GOLDEN_SHOVEL
  - - GOLDEN_HOE

  - - DIAMOND_SWORD
  - - DIAMOND_PICKAXE
  - - DIAMOND_AXE
  - - DIAMOND_SHOVEL
  - - DIAMOND_HOE

  - - LEATHER_HORSE_ARMOR
  - - IRON_HORSE_ARMOR
  - - GOLDEN_HORSE_ARMOR
  - - DIAMOND_HORSE_ARMOR

  - - TURTLE_HELMET

  - - LEATHER_HELMET
  - - LEATHER_CHESTPLATE
  - - LEATHER_LEGGINGS
  - - LEATHER_BOOTS

  - - CHAINMAIL_HELMET
  - - CHAINMAIL_CHESTPLATE
  - - CHAINMAIL_LEGGINGS
  - - CHAINMAIL_BOOTS

  - - IRON_HELMET
  - - IRON_CHESTPLATE
  - - IRON_LEGGINGS
  - - IRON_BOOTS

  - - GOLDEN_HELMET
  - - GOLDEN_CHESTPLATE
  - - GOLDEN_LEGGINGS
  - - GOLDEN_BOOTS

  - - DIAMOND_HELMET
  - - DIAMOND_CHESTPLATE
  - - DIAMOND_LEGGINGS
  - - DIAMOND_BOOTS

  - - BUCKET
  - - WATER_BUCKET
  - - LAVA_BUCKET
  - - MILK_BUCKET

  - - PUFFERFISH_BUCKET
    - SALMON_BUCKET
    - COD_BUCKET
    - TROPICAL_FISH_BUCKET

  - - FLINT_AND_STEEL
    - SHEARS

  - - FISHING_ROD
    - CARROT_ON_A_STICK

  - - COMPASS
    - CLOCK

  - - LEAD
    - NAME_TAG
    - SADDLE

  - - TRIDENT
  - - TOTEM_OF_UNDYING

  - - BOW
    - CROSSBOW
    - ARROW
  - - SHIELD

  - - GOLDEN_APPLE
    - ENCHANTED_GOLDEN_APPLE
    - GLISTERING_MELON_SLICE
    - GOLDEN_CARROT

  - - FIREWORK_ROCKET
    - FIREWORK_STAR

  - - MUSIC_DISC_13
    - MUSIC_DISC_11
    - MUSIC_DISC_CAT
    - MUSIC_DISC_BLOCKS
    - MUSIC_DISC_CHIRP
    - MUSIC_DISC_FAR
    - MUSIC_DISC_MALL
    - MUSIC_DISC_MELLOHI
    - MUSIC_DISC_STAL
    - MUSIC_DISC_STRAD
    - MUSIC_DISC_WARD
    - MUSIC_DISC_WAIT